### ISSUE TITLE
list of up coming events

### ISSUE THREAD

**Issue by Bryony-B** [Bryony-B/project-planning-demo#1]
**User Story**

As a local resident I want to see a list of upcoming community events so that I can find interesting events to attend.

**Acceptance Criteria**

- [ ] the homepage displays a list of upcoming community events.
- [ ] Each event listing includes the event name, date and a brief description.
- [ ] The list is responsive and looks good on all device sizes.

**Tasks**

- [ ] Add an html section on the homepage dedicated to upcoming community events
- [ ] style the event listing using bootstrap
- [ ] add some sample events including event name , date, time, and a brief description.
